### ISSUE TITLE
grafana datasource not being out of the box

### ISSUE THREAD

**Issue by fsismondi** [camptocamp/devops-stack-module-thanos#21]
With devops-stack v0 we used to have by default a grafana_datasource config map declaring url: http://thanos-query.thanos:9090
This is not being created anymore

**Comment by lentidas** [comment]
The datasource is actually added on the kube-prometheus-stack module. I think these lines is what you are referring to: https://github.com/camptocamp/devops-stack-module-kube-prometheus-stack/blob/c788c4e32ef1c30e4222aa1305ffb1b35b20bb8b/local.tf#L105-L121
